### ISSUE TITLE
Error when loading MBNet model

### ISSUE THREAD

**Issue by akefhabbal-qu** [anish-lakkapragada/ActivRecognition-Autism-Diagnosis#3]
I am getting the following error when I load the MBNet model.
OSError: Cannot parse keras metadata at path MBNet\keras_metadata.pb: Received error: Error parsing message with type 'third_party.py.keras.protobuf.SavedMetadata'

**Comment by walidoj** [comment]
I am getting the following error when I load the MBNet model.
OSError: Cannot parse keras metadata at path MBNet\keras_metadata.pb: Received error: Error parsing message with type 'third_party.py.keras.protobuf.SavedMetadata'
